-- three_d_models
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (1, 'halite_germany', '3d-models/halite_germany.glb', NULL, 0, 1, '2026-05-23 10:56:16', '2026-05-23 10:56:16');
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (2, 'hematite', '3d-models/hematite.glb', NULL, 0, 1, '2026-05-23 10:56:16', '2026-05-23 10:56:16');
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (3, 'iron_ore', '3d-models/iron_ore.glb', NULL, 0, 1, '2026-05-23 10:56:28', '2026-05-23 10:56:28');
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (4, 'magnetite', '3d-models/magnetite.glb', NULL, 0, 1, '2026-05-23 10:56:28', '2026-05-23 10:56:28');
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (5, 'rock_salt', '3d-models/rock_salt.glb', NULL, 0, 1, '2026-05-23 10:56:28', '2026-05-23 10:56:28');
INSERT OR IGNORE INTO three_d_models (id, slug, model_path, element_id, sort_order, is_active, created_at, updated_at) VALUES (6, 'zinc_ore', '3d-models/zinc_ore.glb', NULL, 0, 1, '2026-05-23 10:56:28', '2026-05-23 10:56:28');

-- three_d_model_translations
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (1, 1, 1, 'Galit (Germaniyadan namuna)', 'Galit — tabiiy tosh tuzi bo''lib, asosan natriy xloriddan (NaCl) iborat bo''lgan juda muhim mineraldir. Ushbu mineral ko''pincha chiroyli kubik kristallar shaklida uchraydi va kimyo sanoatida xlor hamda o''yuvchi natriy kabi moddalarni olishda eng asosiy xomashyo hisoblanadi. O''zbekiston va Qoraqalpog''istonda, xususan, Orolbo''yi hududlarida yirik va toza galit konlari mavjud bo''lib, ulardan olingan sifatli tuz sanoat va xo''jalikda juda keng qo''llaniladi.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (2, 1, 2, 'Галит (Образец из Германии)', 'Галит — это природная каменная соль, состоящая в основном из хлорида натрия (NaCl) и являющаяся жизненно важным минералом. Этот минерал часто встречается в виде красивых кубических кристаллов и служит основным сырьем в химической промышленности для получения хлора и каустической соды. Крупные месторождения галита расположены в Узбекистане и Каракалпакстане, особенно в Приаралье, где соль активно добывается для пищевых и промышленных целей.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (3, 1, 3, 'Halite (Sample from Germany)', 'Halite is a natural rock salt mineral composed primarily of sodium chloride (NaCl) and is essential for human life. It typically forms beautiful cubic crystals and serves as a fundamental raw material in the chemical industry for producing chlorine and sodium hydroxide. Large and pure halite deposits are found in Uzbekistan and Karakalpakstan, especially near the Aral Sea, where it is mined for domestic and industrial use.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (4, 2, 1, 'Gematit', 'Gematit — temirning eng muhim va tabiatda keng tarqalgan oksidli rudalaridan biri (Fe₂O₃) hisoblanadi. U to''q qizildan to qora ranggacha bo''lib, nomi grekcha "hema" — qon so''zidan olingan, chunki maydalanganda qizil rangli kukun hosil qiladi. Qoraqalpog''istondagi Tebinbuloq konida gematit va magnetit aralashmasidan iborat ulkan temir rudasi zaxiralari mavjud bo''lib, ular mamlakat sanoatida muhim ahamiyatga ega.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (5, 2, 2, 'Гематит', 'Гематит — один из важнейших и наиболее распространенных оксидных минералов железа (Fe₂O₃). Он имеет окраску от темно-красного до стального черного цвета, а его название происходит от греческого слова «гема» — кровь, так как при истирании он дает характерный красный порошок. В Каракалпакстане на крупном месторождении Тебинбулак сосредоточены огромные запасы железной руды, содержащей гематит, что важно для промышленности.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (6, 2, 3, 'Hematite', 'Hematite is one of the most important and widespread iron oxide minerals (Fe₂O₃) found in nature. Ranging in color from dark red to metallic black, its name comes from the Greek word "hema" meaning blood, because it leaves a reddish powder when scratched. In Karakalpakstan, the massive Tebinbulak deposit contains vast reserves of iron ore rich in hematite, representing a strategic resource.', '2026-05-23 10:56:16', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (7, 3, 1, 'Temir rudasi', 'Temir rudasi — tarkibida sanoat miqyosida temir metallini ajratib olish iqtisodiy jihatdan foydali bo''lgan mineral va tog'' jinslarining tabiiy birikmasidir. Undan asosan kundalik hayotimizda zarur bo''lgan cho''yan va po''lat ishlab chiqarishda keng foydalaniladi. Qoraqalpog''istonning Qorao''zak tumanidagi Tebinbuloq koni respublikamizdagi eng yirik konlardan bo''lib, u mamlakatimiz metallurgiya va mashinasozlik sanoati rivojida strategik ahamiyatga ega.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (8, 3, 2, 'Железная руда', 'Железная руда — это природные минеральные образования, содержащие железо в таких количествах, при которых его извлечение является экономически выгодным. В основном добытая руда используется для выплавки чугуна и стали, необходимых в строительстве. Месторождение Тебинбулак в Караузякском районе Каракалпакстана является крупнейшим в стране и имеет стратегическое значение для развития всей тяжелой промышленности Узбекистана.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (9, 3, 3, 'Iron ore', 'Iron ore is a natural mineral formation containing iron in sufficient quantities to make industrial extraction economically viable. It is primarily used to produce pig iron and steel, which are essential for modern construction and infrastructure. The Tebinbulak deposit in the Karauzyak district of Karakalpakstan is the largest in Uzbekistan, playing a strategic role in the nation''s metallurgical development.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (10, 4, 1, 'Magnetit', 'Magnetit — tarkibida eng ko''p temir saqlovchi va kuchli tabiiy magnit xususiyatiga ega bo''lgan ajoyib mineraldir (Fe₃O₄). U qora rangli, metall yaltiroqligiga ega bo''lib, qadimgi dengizchilar tomonidan kompas millarini yasashda va navigatsiyada foydalanilgan. Qoraqalpog''istondagi Tebinbuloq konining asosiy qismini aynan titanomagnetit rudalari tashkil etadi va ularni qayta ishlab, yuqori sifatli po''lat va vanadiy olinadi.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (11, 4, 2, 'Магнетит', 'Магнетит — минерал черного цвета с сильными естественными магнитными свойствами, содержащий наибольшее количество железа (Fe₃O₄). Его металлический блеск и магнетизм способствовали изобретению компаса и развитию древней навигации. Основу месторождения Тебинбулак в Каракалпакстане составляют именно титаномагнетитовые руды, из которых в процессе переработки получают высококачественную сталь и ценный металл ванадий.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (12, 4, 3, 'Magnetite', 'Magnetite is a black iron oxide mineral (Fe₃O₄) with strong natural magnetic properties and the highest iron content among all ores. Its unique magnetic behavior historically led to the invention of the compass and revolutionized early navigation. The Tebinbulak deposit in Karakalpakstan consists mainly of titanomagnetite ores, which are processed to extract high-quality steel and valuable vanadium.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (13, 5, 1, 'Tosh tuzi', 'Tosh tuzi — galit mineralining massiv tog'' jinsi shaklidagi ko''rinishi bo''lib, biz har kuni ovqatga qo''shadigan oddiy osh tuzidir. U nafaqat oziq-ovqat sanoatida, balki kimyoviy birikmalar sintezida hamda qishda yo''llarni muzlashdan tozalashda keng ishlatiladi. Qoraqalpog''istondagi Barsoyo''lmas sho''rxonasi ulkan tosh tuzi zaxirasiga ega bo''lib, u mashhur Qo''ng''irot soda zavodi uchun eng asosiy xomashyo manbai bo''lib xizmat qiladi.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (14, 5, 2, 'Каменная соль', 'Каменная соль — осадочная горная порода, состоящая преимущественно из минерала галита, известная каждому из нас как обычная поваренная соль. Она используется не только в кулинарии, но и в химическом производстве, а также в дорожном хозяйстве. Солончак Барсакельмес в Каракалпакстане хранит колоссальные запасы каменной соли, являясь главным источником сырья для Кунградского содового завода.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (15, 5, 3, 'Rock salt', 'Rock salt is a sedimentary rock composed chiefly of the mineral halite, widely recognized as common table salt. Beyond culinary applications, it is extensively used in the chemical industry for synthesizing compounds and for winter road de-icing. The Barsakelmes salt flat in Karakalpakstan contains massive deposits of rock salt, serving as the primary raw material source for the Kungrad Soda Plant.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (16, 6, 1, 'Rux rudasi', 'Rux rudasi — tarkibida rux metalli mavjud bo''lgan tabiiy birikma bo''lib, uning asosiy manbai sfalerit (ZnS) mineralidir. Rux metalli po''lat va temir buyumlarni zanglashdan saqlash uchun ruxlash vaqtida hamda jez (latun) kabi foydali qotishmalar tayyorlashda keng qo''llaniladi. O''zbekiston polimetall konlaridan qazib olinadigan rux rudasi mamlakatimiz avtomobilsozlik va qurilish materiallari ishlab chiqarish sanoatida katta ahamiyatga ega.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (17, 6, 2, 'Цинковая руда', 'Цинковая руда — природное сырье, содержащее цинк в концентрациях, пригодных для промышленного извлечения, где главным минералом является сфалерит (ZnS). Цинк крайне важен для оцинковки железа с целью защиты от ржавчины и создания сплавов, таких как латунь. Добываемый на рудниках Узбекистана цинк широко применяется в отечественном машиностроении, электротехнике и строительной индустрии.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');
INSERT OR IGNORE INTO three_d_model_translations (id, three_d_model_id, language_id, name, description, created_at, updated_at) VALUES (18, 6, 3, 'Zinc ore', 'Zinc ore is a natural mineral source containing zinc, most commonly represented by the mineral sphalerite (ZnS). Zinc is highly valued for galvanizing iron and steel to prevent rusting, as well as for making useful alloys like brass. Extracted from polymetallic deposits in Uzbekistan, zinc plays an important role in the national automotive, electrical, and construction industries.', '2026-05-23 10:56:28', '2026-06-03 06:38:23');